apiVersion: apps/v1 # Kubernetes API version
kind: Deployment  # Kubernetes resource kind we are creating
metadata:
  name: store-deployment
spec:
  selector:
    matchLabels:
      app: store
  replicas: 5 # Number of replicas that will be created for this deployment
  template:
    metadata:
      labels:
        app: store
    spec:
      containers:
      - name: store
        image: francescococo8/store-image-docker:v3 # Image that will be used to containers in the cluster
        ports:
        - containerPort: 80 # The port that the container is running on in the cluster
---

kind: Service  # Kubernetes API version
apiVersion: v1 # Kubernetes resource kind we are creating
metadata:
  name: store-service
spec:
  selector:
    app: store
  ports:
  - protocol: TCP
    name: http
    port: 80   # The port that the service is running on in the cluster
    targetPort: 80   # The port exposed by the service
    nodePort: 31000
  type: NodePort     # type of the service.